runtime: python
env: flex
entrypoint: gunicorn -b :$PORT web:app

runtime_config:
  python_version: 3.6

# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
